import type { Metadata } from "next";
import { dmSans } from "@/src/styles/font";
import "../styles/globals.css";
import StateWraper from "@/src/state/stateWraper";
import { ToastContainer } from "react-toastify";
import Header from "@/src/components/header";
import Footer from "@/src/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable}  antialiased`}>
        <StateWraper>
          <Header />
          {children}
          <Footer />
        </StateWraper>
        <ToastContainer />
      </body>
    </html>
  );
}
